import enum
from PyQt6.QtCore import pyqtSignal

class View(enum.Enum):
    Upload   = ...
    Load     = ...
    Result   = ...
    EditCrop = ...
    EditText = ...
    Merge    = ...

# Makes any object that inherits this to implement the swap signal.
class ViewWidget:
    swap = pyqtSignal(View)
